{{- $redlinc := .Values.microservice.name -}}
{{- $env := .Values.environment.type -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redlinc-{{ $redlinc }}
  labels:
    app: {{ .Values.app.name  }}
    component: {{ $redlinc }}
    environment: {{ $env }}
    version: {{ .Values.microservice.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       component: {{ $redlinc }}
       environment: {{ $env }}
       version: {{ .Values.microservice.tag | quote }}
  template:
    metadata:
      labels:
        component: {{ $redlinc }}
        environment: {{ $env }}
        version: {{ .Values.microservice.tag | quote }}
    spec:
      containers:
        - name: redlinc-{{ $redlinc }}-img
          image: "{{ .Values.microservice.repository }}:{{ .Values.microservice.tag }}"
          imagePullPolicy: {{ .Values.microservice.pullPolicy }}
          ports:
          {{- range .Values.microservice.myports }}
          - containerPort: {{ .port }}
            protocol: {{ .protocol }}
            name: {{ .name }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
      - name: {{ .Values.microservice.registrysecret }}


