---
- set_fact:
    path_helm: "{{ item.directory }}"
  when: repos is defined
  with_items: "{{ repos }}"
  tags:
    - helm
  vars:
    helm_path: ./helm/deploy/

- name: Updating Inventory
  yedit:
    src: "{{workdir}}/inventory.yml"
    key: images.{{SERVICE_NAME}}.version
    value: "{{IMAGE_VER}}"
  register: update_inventory
  tags:
   - inventory


- name: Writing vault pass to file
  shell: "echo {{ vaultpass }} > .vaultpass"
  tags:
    - helm


- name: Decrypting Kubeconfig
  shell: "ansible-vault decrypt {{workdir}}/kubeconfig --vault-password-file  .vaultpass"
  ignore_errors: True
  tags:
    - helm


- name: Injecting Kubeconfig
  set_fact:
    KUBECONFIG_FULLPATH: "{{workdir}}/kubeconfig"
  tags:
   - helm


- name: Deleting Old Charts
  command: helm delete "{{item.key}}" 

  register: helm_del_results
  changed_when: "'not found' not in helm_del_results.stderr_lines"
  failed_when: "helm_del_results.rc != 0 and 'not found' not in helm_del_results.stderr"
  loop: "{{ lookup('dict', images, wantlist=True) }}"
  tags:
   - helm
  environment:
    KUBECONFIG: "{{ KUBECONFIG_FULLPATH }}"
    TILLER_NAMESPACE: "{{TILLER_NAMESPACE}}"


- name: Installing Charts
  when: images is defined
  command: helm install --name "{{item.key}}"  --values="../{{ item.value.value_name }}" --set microservice.repository="{{item.value.image}}" --set microservice.tag="{{item.value.version}}" "../helm/deploy/{{item.value.chart_name}}" 
  register: helm_install_results
  changed_when: "'already exists' not in helm_install_results.stderr_lines"
  failed_when: "helm_install_results.rc != 0 and 'already exists' not in helm_install_results.stderr"
  loop: "{{ lookup('dict', images, wantlist=True) }}"
  tags:
   - helm
  environment:
    KUBECONFIG: "{{ KUBECONFIG_FULLPATH }}"
    TILLER_NAMESPACE: "{{TILLER_NAMESPACE}}"


- name: Upgrading Charts
  when: images is defined 
  command: helm upgrade  --force  "{{item.key}}"  -f "../{{ item.value.value_name }}" --set microservice.repository="{{item.value.image}}" --set microservice.tag="{{item.value.version}}" "../{{../helm/deploy}}/{{item.value.chart_name}}"  
  register: helm_upgrade_results
  changed_when: "'already exists'  in helm_upgrade_results.stderr_lines"
  failed_when: "helm_upgrade_results.rc != 0 and 'already exists' not in helm_upgrade_results.stderr"
  loop: "{{ lookup('dict', images, wantlist=True) }}"
  tags:
   - helm
  environment:
    KUBECONFIG: "{{ KUBECONFIG_FULLPATH }}"
    TILLER_NAMESPACE: "{{TILLER_NAMESPACE}}"

