---

- name: Creating Service Account
  command: kubectl create serviceaccount tiller
  register: kubectl_svac_results
  changed_when: "'already exists' not in kubectl_svac_results.stderr_lines"
  failed_when: "kubectl_svac_results.rc != 0 and 'already exists' not in kubectl_svac_results.stderr"

- name: Configuring RBAC
  command: kubectl apply -f "{{ role_path }}/files/tiller.yaml"
  register: kubectl_tiller_results
  changed_when: " 'already installed' not in kubectl_tiller_results.stdout"
  

- name: Initializing Tiller
  command: helm init --service-account tiller --tiller-namespace "{{ TILLER_NAMESPACE }}"
  register: helm_init_result
  changed_when: "'already installed' not in helm_init_result.stdout"

- name: Wait for Tiller
  command: sleep 15
  register: " 'already installed' not in kubectl_tiller_results.stdout"
  
- name: Getting Helm Version
  command: helm version  --tiller-namespace "{{ TILLER_NAMESPACE }}"
  register: helm_version_result
  
- debug:
    var:  helm_version_result.stdout_lines 


- name: Listing Installed Helm Charts
  command: helm ls --tiller-namespace "{{ TILLER_NAMESPACE }}"
  register: helm_list_results
- debug:
    var: helm_list_results.stdout_lines
 # changed_when: False


  
