kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tillerrb
subjects:
- kind: ServiceAccount
  name: tiller
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ns-contributor
  apiGroup: ""
