#TODO Verfiy values before deploy it
environment:
  type: dev

app:
  name: nimrodops

replicaCount: 1

microservice:
  name: main
  repository: hub.docker.com/nimrodops/nginx-app
  tag: 
  pullPolicy: Always
  registrysecret: hub-credentials

  myports:
    - name: http
      port: 8080
      protocol: TCP


service:
  type: ClusterIP
  port:
    name: http
    containerPort: 8080
    servicePort: 8080
    protocol: TCP

varEnv:
  enabled: true


